/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientserverchat;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.*;
import java.awt.*;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.text.BadLocationException;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.sound.sampled.*;
import java.nio.file.Files;
import java.nio.file.Paths;

        
/**
 *
 * @author Livingstone Righa maghanga
 */
public class ServerForm extends javax.swing.JFrame {

    /**
     * Creates new form ServerForm
     */
    static ServerSocket ss;
    static Socket s;
    static DataInputStream DI;
    static DataOutputStream dos;
    static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
    static StringBuilder chatHTML = new StringBuilder("<html><head><style>body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 15px; background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); } .message-container { margin-bottom: 12px; display: flex; align-items: flex-end; } .sent { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 12px 16px; border-radius: 18px 18px 4px 18px; max-width: 75%; word-wrap: break-word; margin-left: auto; box-shadow: 0 2px 8px rgba(102, 126, 234, 0.3); animation: slideIn 0.3s ease-out; } .received { background-color: #ffffff; color: #333; padding: 12px 16px; border-radius: 18px 18px 18px 4px; max-width: 75%; word-wrap: break-word; margin-right: auto; box-shadow: 0 2px 8px rgba(0,0,0,0.1); border-left: 3px solid #667eea; animation: slideIn 0.3s ease-out; } @keyframes slideIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } } .timestamp { font-size: 11px; color: #999; margin: 4px 0; text-align: center; letter-spacing: 0.5px; } .avatar { width: 36px; height: 36px; border-radius: 50%; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); margin: 0 10px; display: flex; align-items: center; justify-content: center; font-weight: bold; color: #fff; font-size: 15px; flex-shrink: 0; } .sent-container { justify-content: flex-end; } .received-container { justify-content: flex-start; }</style></head><body>");
    static JEditorPane chatPane;
    
    
    public ServerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chatPane = new javax.swing.JEditorPane();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonFile = new javax.swing.JButton();
        headerLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server Chat ");
        setSize(500, 650);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(245, 247, 250));
        getContentPane().setLayout(null);

        headerLabel.setText("Chat with Client");
        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18));
        headerLabel.setForeground(new java.awt.Color(51, 51, 51));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 10, 10, 10));
        getContentPane().add(headerLabel);
        headerLabel.setBounds(0, 0, 500, 50);

        statusLabel.setText("Waiting for client...");
        statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 11));
        statusLabel.setForeground(new java.awt.Color(150, 150, 150));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(statusLabel);
        statusLabel.setBounds(0, 50, 500, 25);

        chatPane.setContentType("text/html");
        chatPane.setEditable(false);
        chatPane.setText(chatHTML.toString() + "</body></html>");
        chatPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(chatPane);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 480, 480);

        jTextField1.setBounds(10, 570, 310, 40);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 13));
        jTextField1.setEnabled(false);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    sendMessage();
                }
            }
        });
        getContentPane().add(jTextField1);

        jButtonFile.setText("File");
        jButtonFile.setBackground(new java.awt.Color(76, 175, 80));
        jButtonFile.setForeground(java.awt.Color.WHITE);
        jButtonFile.setEnabled(false);
        jButtonFile.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jButtonFile.setFocusPainted(false);
        jButtonFile.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jButtonFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileAction(evt);
            }
        });
        getContentPane().add(jButtonFile);
        jButtonFile.setBounds(330, 570, 60, 40);

        jButton1.setText("SEND");
        jButton1.setBackground(new java.awt.Color(102, 126, 234));
        jButton1.setForeground(java.awt.Color.WHITE);
        jButton1.setEnabled(false);
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13));
        jButton1.setFocusPainted(false);
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 570, 90, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void sendMessage() {
        if (dos == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Not connected to client yet.", "Connection Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String msgout = jTextField1.getText().trim();
        if (msgout.isEmpty()) {
            return;
        }

        try {
            dos.writeUTF(msgout);
            String escapedMsg = msgout.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;").replace("\n", "<br>");
            chatHTML.append("<div class='timestamp'>").append(LocalDateTime.now().format(formatter)).append("</div><div class='message-container sent-container'><div class='avatar'>Y</div><div class='sent'>").append(escapedMsg).append("</div></div><br clear='both'>");
            chatPane.setText(chatHTML.toString() + "</body></html>");
            try { chatPane.setCaretPosition(chatPane.getDocument().getLength()); } catch (Exception e) {}
            jTextField1.setText("");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Unable to send message: " + e.getMessage(), "Send Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setConnected(boolean connected) {
        jTextField1.setEnabled(connected);
        jButton1.setEnabled(connected);
        jButtonFile.setEnabled(connected);
        statusLabel.setText(connected ? "Connected" : "Waiting for client...");
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sendMessage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sendFileAction(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select File to Send");
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            new Thread(() -> sendFile(selectedFile)).start();
        }
    }

    private void sendFile(File file) {
        try {
            byte[] fileData = Files.readAllBytes(file.toPath());
            synchronized(dos) {
                dos.writeUTF("FILE:" + file.getName() + ":" + fileData.length);
                dos.flush();
                dos.write(fileData);
                dos.flush();
            }
            
            String msg = "📎 Sent file: " + file.getName() + " (" + formatFileSize(file.length()) + ")";
            String escapedMsg = msg.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
            chatHTML.append("<div class='timestamp'>").append(LocalDateTime.now().format(formatter)).append("</div><div class='message-container sent-container'><div class='avatar'>Y</div><div class='sent'>").append(escapedMsg).append("</div></div><br clear='both'>");
            
            javax.swing.SwingUtilities.invokeLater(() -> {
                chatPane.setText(chatHTML.toString() + "</body></html>");
                try { chatPane.setCaretPosition(chatPane.getDocument().getLength()); } catch (Exception e) {}
            });
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error sending file: " + e.getMessage(), "File Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void playNotificationSound() {
        try {
            AudioFormat audioFormat = new AudioFormat(8000, 8, 1, true, false);
            DataLine.Info info = new DataLine.Info(SourceDataLine.class, audioFormat);
            SourceDataLine line = (SourceDataLine) AudioSystem.getLine(info);
            line.open(audioFormat);
            line.start();
            
            int duration = 200;
            int samples = (int)(audioFormat.getSampleRate() * duration / 1000);
            byte[] soundData = new byte[samples];
            
            for (int i = 0; i < samples; i++) {
                soundData[i] = (byte)(Math.sin(2 * Math.PI * 800 * i / audioFormat.getSampleRate()) * 100);
            }
            
            line.write(soundData, 0, soundData.length);
            line.drain();
            line.close();
        } catch (Exception e) {
            // Silent fail for sound
        }
    }

    private void handleIncomingFile(String fileHeader) {
        try {
            String[] parts = fileHeader.split(":");
            String fileName = parts[1];
            long fileSize = Long.parseLong(parts[2]);
            
            byte[] fileData = new byte[(int)fileSize];
            int bytesRead = 0;
            while (bytesRead < fileSize) {
                int read = DI.read(fileData, bytesRead, (int)(fileSize - bytesRead));
                if (read == -1) break;
                bytesRead += read;
            }
            
            String downloadDir = System.getProperty("user.home") + File.separator + "Downloads";
            File downloadFile = new File(downloadDir, fileName);
            Files.write(downloadFile.toPath(), fileData);
            
            playNotificationSound();
            
            String msg = "📎 Received file: " + fileName + " (" + formatFileSize(fileSize) + ") - Saved to Downloads";
            String escapedMsg = msg.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
            chatHTML.append("<div class='timestamp'>").append(LocalDateTime.now().format(formatter)).append("</div><div class='message-container received-container'><div class='avatar'>C</div><div class='received'>").append(escapedMsg).append("</div></div><br clear='both'>");
        } catch (Exception e) {
            javax.swing.SwingUtilities.invokeLater(() -> 
                JOptionPane.showMessageDialog(null, "Error receiving file: " + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE)
            );
        }
    }

    private String formatFileSize(long bytes) {
        if (bytes < 1024) return bytes + " B";
        int units = 1024;
        if (bytes < units * 1024) return String.format("%.1f KB", bytes / (double) units);
        if (bytes < units * units * 1024) return String.format("%.1f MB", bytes / (double) (units * units));
        return String.format("%.1f GB", bytes / (double) (units * units * units));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ServerForm serverForm = new ServerForm();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                serverForm.setVisible(true);
            }
        });
        
        new Thread(() -> {
            String msgin = "";
            try {
        /*
         connecting the server socket with port 1201
         Server socket should accept the connection
        
         */
            ss = new ServerSocket(1201);
            s = ss.accept();
            DI = new DataInputStream(s.getInputStream());
            dos = new DataOutputStream(s.getOutputStream());
            javax.swing.SwingUtilities.invokeLater(() -> serverForm.setConnected(true));
        
            while(!msgin.equals("exit")){
            
            msgin = DI.readUTF();
            
            if (msgin.startsWith("FILE:")) {
                serverForm.handleIncomingFile(msgin);
            } else {
                serverForm.playNotificationSound();
                String escapedMsg = msgin.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;").replace("\n", "<br>");
                chatHTML.append("<div class='timestamp'>").append(LocalDateTime.now().format(formatter)).append("</div><div class='message-container received-container'><div class='avatar'>C</div><div class='received'>").append(escapedMsg).append("</div></div><br clear='both'>");
            }
            
            javax.swing.SwingUtilities.invokeLater(() -> {
                chatPane.setText(chatHTML.toString() + "</body></html>");
                try { chatPane.setCaretPosition(chatPane.getDocument().getLength()); } catch (Exception e) {}
            });
            }
                
                
            } catch(Exception e) {
                javax.swing.SwingUtilities.invokeLater(() -> serverForm.statusLabel.setText("Connection failed"));
                JOptionPane.showMessageDialog(null, "Server connection error: " + e.getMessage(), "Connection Error", JOptionPane.ERROR_MESSAGE);
            }
        }).start();
    }
    
    

    // Variables declaration - do not modify//
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//
}
